export const FETCH_USER = 'FETCH_USER';
export const FETCH_RETAILER_PRODUCTS = 'FETCH_RETAILER_PRODUCTS'
export const FETCH_RETAILER_ORDERS = 'FETCH_RETAILER_ORDERS';
export const UPDATE_RETAILER_ORDERS = 'UPDATE_RETAILER_ORDERS';
export const LOAD_RETAILER = 'LOAD_RETAILER';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_RETAILER = 'UPDATE_RETAILER';



export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
export const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const CART_QUANTITY_SETTER = 'CART_QUANTITY_SETTER';


export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';



export const FLASH = 'FLASH';
export const UNFLASH = 'UNFLASH';



export const FETCH_CUSTOMER_ORDER = 'FETCH_CUTOMER_ORDER';
export const FETCH_RETAILER_ORDER = 'FETCH_RETAILER_ORDER';
export const UPDATE_RETAILER_ORDER = 'UPDATE_RETAILER_ORDER';
export const FETCH_CUSTOMER_SECTION = 'FETCH_CUSTOMER_SECTION';


export const FETCH_SERVICE = 'FETCH_SERVICE';
export const LOAD_SERVICE = 'LOAD_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const FETCH_SERVICE_RETAILER_ORDERS = 'FETCH_SERVICE_RETAILER_ORDERS';
export const FETCH_SERVICE_CUSTOMER_ORDERS = 'FETCH_SERVICE_CUSTOMER_ORDERS';
export const FETCH_SERVICE_SERVICE_ORDERS = 'FETCH_SERVICE_SERVICE_ORDERS';






export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_CATEGORY = 'SEARCH_CATEGORY';